name: bigboxx-mqtt
base: core18
version: git
summary: MQTT driver for BigBoxx
description: |
  e-Cattle BigBoxx is a middleware to receive, rank, segment, persist and provide sensory data
  for IoT applications in livetstock farms.

grade: devel
confinement: devmode

apps:
  mqtt-driver:
    command: bin/mqtt-driver.py
    daemon: simple
    restart-condition: always 
    plugs: [network,network-bind,mount-observe,network-observe,system-observe]

parts:
  mqtt-driver:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - paho-mqtt
      - requests
      - redis
