name: bigboxx-mqtt
base: core18
version: '0.1'
summary: MQTT driver for BigBoxx
description: |
  e-Cattle BigBoxx is a middleware to receive, rank, segment, persist and provide sensory data
  for IoT applications in livetstock farms.

grade: devel
confinement: devmode

parts:
  mqtt-driver:
    plugin: python
    python-version: python3
    source: .

apps:
  mqtt-driver:
    command: python3 mqtt-driver
